name: Deploy to Amazon EC2 

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: ap-northeast-2

permissions:
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to EC2
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.EC2_HOST }}
        USER: ${{ secrets.EC2_USER }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          # Navigate to the project directory
          cd ~/screenwiper_ai_v2 &&
          # Pull the latest changes
          git pull origin main &&
          # Install or update dependencies
          pip install -r requirements.txt &&
          # Restart the application (adjust based on your setup)
          pkill -f "python main.py" || true
          nohup python main.py > nohup.out 2>&1 &
        '

    - name: Clean up
      if: always()
      run: rm -f private_key
