name: Deploy to Amazon EC2
on:
    push:
        branches: ['main']
env:
    AWS_REGION: ap-northeast-2
permissions:
    contents: read
jobs:
    deploy:
        name: Deploy
        runs-on: ubuntu-latest
        environment: production
        steps:
            - name: Checkout code
              uses: actions/checkout@v4
            - name: Configure AWS credentials
              uses: aws-actions/configure-aws-credentials@v1
              with:
                  aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                  aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                  aws-region: ${{ env.AWS_REGION }}
            - name: Deploy to EC2
              env:
                  PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
                  HOST: ${{ secrets.EC2_HOST }}
                  USER: ${{ secrets.EC2_USER }}
                  AWS_DEFAULT_REGION: ap-northeast-2
              run: |
                  echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
                  ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
                    set -e
                    echo "Navigating to project directory"
                    cd ~/screenwiper_ai_v2 || { echo "Failed to change directory"; exit 1; }
                    
                    echo "Pulling latest changes"
                    git pull origin main || { echo "Failed to pull changes"; exit 1; }

                    echo "Stopping any existing uvicorn processes"
                    pkill -f "uvicorn main:app" || echo "No existing process found"

                    echo "Installing or updating dependencies"
                    pip install -r requirements.txt || { echo "Failed to install dependencies"; exit 1; }
                    
                    echo "Starting new process"
                    nohup uvicorn main:app --host=0.0.0.0 --port=3000 > app.log 2>&1 &
                    
                    echo "Waiting for application to start"
                    sleep 15
                    
                    echo "Checking process status"
                    if pgrep -f "uvicorn main:app"; then
                      echo "Application is running"
                      tail -n 50 app.log
                    else
                      echo "Application failed to start"
                      tail -n 100 app.log
                      exit 1
                    fi
                    
                    echo "Deployment completed"
                  '
            - name: Cleanup
              if: always()
              run: rm -f private_key
